# Sample .travis.yml for R projects +
# https://github.com/travis-ci/travis-ci/issues/5775

language: r
r: bioc-devel

warnings_are_errors: true

sudo: required

cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gsl-bin libgsl2 libgsl-dev r-cran-rmpi
  
install:
  - Rscript -e 'install.packages(c("devtools","knitr","testthat","roxygen2","Cairo","Rmpi"));source("http://bioconductor.org/biocLite.R");options(repos=biocinstallRepos());biocLite(c("BiocStyle","CGHregions","limma"));devtools::install_deps("ADaCGH2")'
 
before_script:
   - R CMD build --keep-empty-dirs ADaCGH2
script:
   - R CMD check --no-vignettes --timings ADaCGH2_*.tar.gz

## I use "no-vignettes", which is the way it is used in BioC, and we built
## the vignette right on top, so this is OK. Moreover, unless we use
## "--no-vignettes" it will fail in travis, as the procedure used in
## Travis confuses ADaCGH2 because of the relative location of files.


## An alternative would be to change directories as in
## https://github.com/travis-ci/travis-ci/issues/5775
## I haven't tried it.

notifications:
  email:
    on_success: change
    on_failure: change



